---
apiVersion: v1
kind: Service
metadata:
  name: agsr-nginx-service
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: agsr-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80